import { useState } from 'react'
import { Check, Clipboard, Cloud, Download, KeyRound, LoaderCircle } from 'lucide-react'
import { createResources, listAccounts, wranglerConfig, type Account, type Resources } from './wizard-api'

function download(name: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'application/json' }))
  const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url)
}

export default function Wizard() {
  const [token, setToken] = useState(''); const [accounts, setAccounts] = useState<Account[]>([]); const [accountId, setAccountId] = useState(''); const [name, setName] = useState('wangwang'); const [resources, setResources] = useState<Resources>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [copied, setCopied] = useState(false)
  const config = resources ? wranglerConfig(resources) : ''
  async function discover() { setBusy(true); setError(''); try { const result = await listAccounts(token); setAccounts(result); setAccountId(result[0]?.id || '') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Token 验证失败') } finally { setBusy(false) } }
  async function provision() { setBusy(true); setError(''); try { setResources(await createResources(token, accountId, name)); setToken('') } catch (reason) { setError(reason instanceof Error ? reason.message : '资源创建失败') } finally { setBusy(false) } }
  async function copy() { await navigator.clipboard.writeText(config); setCopied(true); setTimeout(() => setCopied(false), 1200) }
  return <main className="wizard"><header><div className="logo">W</div><div><strong>Wangwang</strong><span>Cloudflare 部署向导</span></div></header><section className="hero"><p className="eyebrow">BROWSER-ONLY DEPLOYMENT</p><h1>部署到你自己的 Cloudflare</h1><p>Token 只在本页内存中使用，直接从浏览器请求 Cloudflare API，不经过 Wangwang 服务器。</p></section><section className="steps"><article className={accounts.length ? 'done' : 'active'}><b>1</b><div><h2><KeyRound />验证 Token</h2><label>Cloudflare API Token<input type="password" value={token} onChange={(event) => setToken(event.target.value)} autoComplete="off" placeholder="粘贴 API Token" /></label><button onClick={() => void discover()} disabled={busy || token.length < 20}>{busy && <LoaderCircle className="spin" />}查询账户</button></div></article>{accounts.length > 0 && !resources && <article className="active"><b>2</b><div><h2><Cloud />创建资源</h2><label>Account<select value={accountId} onChange={(event) => setAccountId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.id}</option>)}</select></label><label>项目名称<input value={name} onChange={(event) => setName(event.target.value)} maxLength={28} /></label><button onClick={() => void provision()} disabled={busy || !accountId}>{busy && <LoaderCircle className="spin" />}创建 D1 / KV / Queue</button></div></article>}{resources && <article className="done"><b>✓</b><div><h2><Check />资源已创建</h2><dl><dt>D1</dt><dd>{resources.database.name}<small>{resources.database.id}</small></dd><dt>KV</dt><dd>{resources.kv.title}<small>{resources.kv.id}</small></dd><dt>Queue</dt><dd>{resources.queue.name}</dd></dl><div className="config-actions"><button onClick={() => void copy()}>{copied ? <Check /> : <Clipboard />}{copied ? '已复制' : '复制 Wrangler 配置'}</button><button onClick={() => download('wrangler.resources.json', config)}><Download />下载配置</button></div><p className="hint">资源创建完成。将配置合并到项目 Wrangler 文件后执行部署。</p></div></article>}</section>{error && <div className="error">{error}</div>}<footer>权限由 Cloudflare 授权；本页面不会保存 Token。</footer></main>
}
